config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  get 'new_releases', to: 'weekly_lists#new_releases'
  get 'releases/:date', to: 'weekly_lists#show'
  resources :creators, only: [:index, :show]
  resources :comics, only: :show
  resources :publishers, only: :index

  get :api, to: 'static_pages#api_doc'
  get :about, to: 'static_pages#about'
  namespace :api do
    namespace :v1 do
      get :weekly_releases, to: "comics#weekly_releases"
      resources :comics, only: [:index]
      resources :publishers, only: [:index]
      resources :creators, only: [:index]
      get :creator, to: "creators#show"
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
  end

  def api_doc
  end

  def about
  end
end

app/views/static_pages/_comics_resource_description.html.slim
h3 Get list of comics
p
  a href='api/v1/comics' grepcomics.io/api/v1/comics
h4 Query params
table.table.table-bordered
  thead
    tr
      th Param
      th Required
      th Description
  tbody
    tr
      td names
      td false
      td Filters publishers by names. Query consists of the list of publishers names, separated by commas. Names are case insensitive.
    tr
      td colspan=3 example: "grepcomics.io/api/v1/comics?key=API_KEY"
h4 Response example
blockquote
  code
    p = '{'
    p &emsp;'total': 2,
    p &emsp;'comics': [
    p &emsp;&emsp;{
    p &emsp;&emsp;&emsp;'name': 'DARK HORSE COMICS',
    p &emsp;&emsp;&emsp;'totalComics': 11,
    p &emsp;&emsp;},
    p &emsp;&emsp;{
    p &emsp;&emsp;&emsp;'name': 'MARVEL COMICS',
    p &emsp;&emsp;&emsp;'totalComics': 28,
    p &emsp;&emsp;},
    p &emsp;]
    p = '}'

app/views/static_pages/_creators_resource_description.html.slim
h3 Get list of creators
p
  a href='api/v1/creators' grepcomics.io/api/v1/creators
h4 Query params
table.table.table-bordered
  thead
    tr
      th Param
      th Required
      th Description
  tbody
    tr
      td names
      td false
      td Filters creators by names. Query consists of the list of creators names, separated by commas. Names are case insensitive.
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/creators?key=API_KEY&names=Michael,grant,ANN"
h4 Response example
blockquote
  code
    p = '{'
    p &emsp;'total': 1,
    p &emsp;'creators': [
    p &emsp;&emsp;{
    p &emsp;&emsp;&emsp;'name': 'Michael DeForge',
    p &emsp;&emsp;&emsp;'totalWriterCredits': 0,
    p &emsp;&emsp;&emsp;'totalArtistCredits': 0,
    p &emsp;&emsp;&emsp;'totalCoverArtistCredits': 1
    p &emsp;&emsp;}
    p &emsp;]
    p = '}'
h3 Get single creator with their comics credits
p
  a href='api/v1/creator' grepcomics.io/api/v1/creator
h4 Query params
table.table.table-bordered
  thead
    tr
      th Param
      th Required
      th Description
  tbody
    tr
      td name
      td true
      td Finds creator by name. Name is case insensitive.
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/creator?key=API_KEY&name=DeForge"
h4 Response example
blockquote
  code
    p = '{'
    p &emsp;'name': 'Michael DeForge',
    p &emsp;'workedForPublishers': ['IMAGE COMICS'],
    p &emsp;'writtenComics': [],
    p &emsp;'drawnComics': [],
    p &emsp;'drawnCovers': [
    p &emsp;&emsp;{
    p &emsp;&emsp;&emsp;'diamond_code': "JUN160636",
    p &emsp;&emsp;&emsp;'title': 'Island',
    p &emsp;&emsp;&emsp;'issue_number': 10,
    p &emsp;&emsp;&emsp;'publisher': 'IMAGE COMICS',
    p &emsp;&emsp;&emsp;'preview': 'The award-winning, oversized comics magazine continues!...',
    p &emsp;&emsp;&emsp;'shipping_date': '2016-08-24'
    p &emsp;&emsp;}
    p &emsp;]
    p = '}'

app/views/static_pages/_description.html.slim
p 
  | All of the data can be accessed via JSON API. It is completely free to use, but you must have a key to access it. I haven't implemented any kind of user registration yet, so if you want a key, send me an email at  
  = link_to 'admin@grepcomics.io'
h4 How to use it:
ol
  li GET http request
  li Content-Type header should be set as 'application/json'
  li 'key' query param should be your API key
  li Make a request to the url beneath, where %resource_name% is the name of the resource that you need. Available resources and their specific query params are listed below.
p
  a href='api/v1/%resource_name%' grepcomics.io/api/v1/%resource_name%
h4 Example request with curl:
p curl -H "Content-Type: application/json" "grepcomics.io/api/v1/creators?key=API_KEY&some_param=some_value"

app/views/static_pages/_list_of_resources.html.slim
h4 List of resources:
.nav-tabs-custom
  ul.nav.nav-tabs
    li.active
      a href="#creators" data-toggle="tab" aria-expanded="true" Creators
    li
      a href="#publishers" data-toggle="tab" aria-expanded="true" Publishers
    li
      a href="#comics" data-toggle="tab" aria-expanded="true" Comics
    li
      a href="#weekly_releases" data-toggle="tab" aria-expanded="true" Weekly Releases
  .tab-content
    .tab-pane.active#creators
      = render 'creators_resource_description'
    .tab-pane#publishers
      = render 'publishers_resource_description'
    .tab-pane#comics
      = render 'comics_resource_description'
    .tab-pane#weekly_releases
      = render 'weekly_releases_resource_description'

app/views/static_pages/_publishers_resource_description.html.slim
h3 Get list of publishers
p
  a href='api/v1/publishers' grepcomics.io/api/v1/publishers
h4 Query params
table.table.table-bordered
  thead
    tr
      th Param
      th Required
      th Description
  tbody
    tr
      td names
      td false
      td Filters publishers by names. Query consists of the list of publishers names, separated by commas. Names are case insensitive.
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/publishers?key=API_KEY&names=dark,marvel,koyama"
h4 Response example
blockquote
  code
    p = '{'
    p &emsp;'total': 2,
    p &emsp;'publishers': [
    p &emsp;&emsp;{
    p &emsp;&emsp;&emsp;'name': 'DARK HORSE COMICS',
    p &emsp;&emsp;&emsp;'totalComics': 11,
    p &emsp;&emsp;},
    p &emsp;&emsp;{
    p &emsp;&emsp;&emsp;'name': 'MARVEL COMICS',
    p &emsp;&emsp;&emsp;'totalComics': 28,
    p &emsp;&emsp;},
    p &emsp;]
    p = '}'

app/views/static_pages/_weekly_releases_resource_description.html.slim
h3 Get list of weekly releases
p Same as comics, but limited to weekly releases
p
  a href='api/v1/weekly_releases' grepcomics.io/api/v1/weekly_releases
h4 Query params
table.table.table-bordered
  thead
    tr
      th Param
      th Required
      th Description
  tbody
    /date
    tr
      td publisher
      td true
      td Specifies the week, when the comics were released. Comics come out on wednesday, so specifying the wednesday day will give you the most accurate results. Date should be in YYYY-MM-DD format.
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/weekly_releases?key=API_KEY&date=2016-08-24"
    /publisher
    tr
      td publisher
      td false
      td Filters comics by publisher. Query consists of the single complete name of the publisher. Case insensitive.
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/weekly_releases?key=API_KEY&publisher=dark%20horse%20comics"
    /title
    tr
      td title
      td false
      td Filters comics by title. Query consists of the single full or partial title of the comic. Case insensitive.
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/weekly_releases?key=API_KEY&title=cerebus"
    /creators
    tr
      td creators
      td false
      td Filters comics by creators with any credits. Query consists of the list of creators names, separated by commas. Names are case insensitive.
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/weekly_releases?key=API_KEY&creators=michael%20deforge,grant,cameron%20stewart"
    /writers
    tr
      td writers
      td false
      td Filters comics by creators, credited as writers. Query consists of the list of creators names, separated by commas. Names are case insensitive.
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/weekly_releases?key=API_KEY&writers=michael%20deforge,grant,cameron%20stewart"
    /artists
    tr
      td artists
      td false
      td Filters comics by creators, credited as artists. Query consists of the list of creators names, separated by commas. Names are case insensitive.
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/weekly_releases?key=API_KEY&artists=michael%20deforge,grant,cameron%20stewart"
    /cover_artists
    tr
      td cover_artists
      td false
      td Filters comics by creators, credited as cover artists. Query consists of the list of creators names, separated by commas. Names are case insensitive.
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/weekly_releases?key=API_KEY&cover_artists=michael%20deforge,grant,cameron%20stewart"
    /has_variant_covers
    tr
      td has_variant_covers
      td false
      td Filters by comics that have variant covers if set as true
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/weekly_releases?key=API_KEY&has_variant_covers=true"
    /issue_number
    tr
      td issue_number
      td false
      td Filters comics by their issue number. Only single issues have issue number.
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/weekly_releases?key=API_KEY&issue_number=3"
    /reprint
    tr
      td reprint
      td false
      td Filters by comics that are reprints if set as true
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/weekly_releases?key=API_KEY&reprint=true"
    /type
    tr
      td type
      td false
      td Filters comics by their format type. Query consists of a single type.
    tr
      td colspan=2 List of possible types:
      td single_issue, hardcover, softcover, trade_paperback, graphic_novel
    tr
      td colspan=2 Example:
      td = "grepcomics.io/api/v1/weekly_releases?key=API_KEY&type=graphic_novel"
h4 Response example
blockquote
  code
    p = '{'
    p &emsp;'total': 1,
    p &emsp;'comics': [
    p &emsp;&emsp;{
    p &emsp;&emsp;&emsp;'diamond_code': 'JUN160636',
    p &emsp;&emsp;&emsp;'title': 'ISLAND',
    p &emsp;&emsp;&emsp;'type': 'single_issue',
    p &emsp;&emsp;&emsp;'issue_number': 10,
    p &emsp;&emsp;&emsp;'publisher': 'IMAGE COMICS',
    p &emsp;&emsp;&emsp;'shipping_date': '2016-08-24',
    p &emsp;&emsp;&emsp;'preview': 'The award winning...',
    p &emsp;&emsp;&emsp;'original_cover_url': 'http://www.previewsworld.com/SiteImage/CatalogImage/STL014313?type=1',
    p &emsp;&emsp;&emsp;'creators': {
    p &emsp;&emsp;&emsp;&emsp;&emsp;'writers': [
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;'name': 'Farel Dalrymple'
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;},
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;'name': 'Fil Barlow'
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;},
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;'name': 'Gael Bertrand'
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;}
    p &emsp;&emsp;&emsp;&emsp;&emsp;],
    p &emsp;&emsp;&emsp;&emsp;&emsp;'artists': [
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;'name': 'Farel Dalrymple'
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;},
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;'name': 'Fil Barlow'
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;},
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;'name': 'Gael Bertrand'
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;}
    p &emsp;&emsp;&emsp;&emsp;&emsp;],
    p &emsp;&emsp;&emsp;&emsp;&emsp;'cover_artists': [
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;{
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;'name': 'Michael DeForge'
    p &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;}
    p &emsp;&emsp;&emsp;&emsp;&emsp;]
    p &emsp;&emsp;&emsp;}
    p &emsp;&emsp;}
    p &emsp;]
    p = '}'

app/views/static_pages/about.html.slim
section.content
  .box
    .box-header
      h3.box-title About
    .box-body
      dl
        dt Created by
        dd
          = 'Vyacheslav Savelyev,  '
          = link_to 'https://github.com/slavone', 'https://github.com/slavone'
        dt Contact me at
        dd = link_to 'admin@grepcomics.io', '#'
        dt Theme by
        dd = link_to 'https://almsaeedstudio.com/', 'https://almsaeedstudio.com/'
      p
        | All the data is being taken from
        a href='http://www.previewsworld.com/' www.previewsworld.com

app/views/static_pages/api_doc.html.slim
section.content
  .box
    .box-header
      h3.box-title API documentation
    .box-body
      = render 'description'
      = render 'list_of_resources'

app/views/static_pages/landing.html.slim
.landing-wrapper
  .text-center
    h1 grepComics
    h3 A convenient tool for browsing comics releases, with the focus on the creators
    br
    = link_to "Go to this week's releases", new_releases_path, class: 'btn btn-info'