config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  get 'new_releases', to: 'weekly_lists#new_releases'
  get 'releases/:date', to: 'weekly_lists#show'
  resources :creators, only: [:index, :show]
  resources :comics, only: :show
  resources :publishers, only: :index

  get :api, to: 'static_pages#api_doc'
  get :about, to: 'static_pages#about'
  namespace :api do
    namespace :v1 do
      get :weekly_releases, to: "comics#weekly_releases"
      resources :comics, only: [:index]
      resources :publishers, only: [:index]
      resources :creators, only: [:index]
      get :creator, to: "creators#show"
    end
  end
end

app/models/weekly_list.rb
# == Schema Information
#
# Table name: weekly_lists
#
#  id             :integer          not null, primary key
#  list           :text
#  wednesday_date :date
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class WeeklyList < ApplicationRecord
  has_many :comics, dependent: :destroy
  has_many :comics_with_no_covers, -> { where no_cover_available: true }, class_name: 'Comic'

  class << self
    def earliest_wednesday_date
      WeeklyList.order(:wednesday_date).limit(1).pluck(:wednesday_date).first
    end

    def current_week_list
      WeeklyList.order(wednesday_date: :desc).first
    end

    def find_by_closest_date(date)
      sanitized_date = Date.parse date

      WeeklyList.order("abs(wednesday_date - date '#{sanitized_date}')").first
    end
  end

  def fetch_comics
    self.comics.eager_load(:publisher)
               .preload(:writers, :artists, :cover_artists)
               .order('publishers.name', :title, :issue_number)
  end

  def all_creators
    Creator.find_by_sql "SELECT DISTINCT creators.*
                        FROM creators
                        JOIN creator_credits
                        ON creator_credits.creator_id = creators.id
                        JOIN comics
                        ON creator_credits.comic_id = comics.id AND comics.weekly_list_id = #{self.id}
                        ORDER BY name"
  end

  def all_publishers
    Publisher.find_by_sql("SELECT DISTINCT publishers.*
                          FROM publishers
                          JOIN comics
                          ON comics.weekly_list_id = #{self.id} AND comics.publisher_id = publishers.id
                          ORDER BY name")
  end
end

app/controllers/weekly_lists_controller.rb
class WeeklyListsController < ApplicationController
  def new_releases
    @weekly_list = WeeklyList.current_week_list
    @comics = @weekly_list&.fetch_comics
    @creators_filters = @weekly_list&.all_creators
    @publishers_filters = @weekly_list&.all_publishers
    render :show
  end

  def show
    @weekly_list = WeeklyList.find_by_closest_date params[:date]
    @comics = @weekly_list&.fetch_comics
    @creators_filters = @weekly_list&.all_creators
    @publishers_filters = @weekly_list&.all_publishers
  end
end

app/views/weekly_lists/new_releases.html.slim
section.content
  .box
    .box-header
      h3.box-title Browse new releases
    .box-body
      table.table.table-bordered.dataTable#releases
        thead
          tr
            th Cover
            th Diamond code
            th Shipping date
            th Title
            th Issue number
            th Publisher
            th Writers
            th Artists
            th Cover artists
        tbody
          - @comics.each do |comic|
            tr data-preview= comic.preview
              td
                img src=comic.cover_image height='330' width='215'
              td = comic.diamond_code
              td = comic.shipping_date
              td = comic.humanized_title
              td = comic.issue_number
              td = comic.publisher&.name
              td = comic.writers&.map(&:name).join(', ')
              td = comic.artists&.map(&:name).join(', ')
              td = comic.cover_artists&.map(&:name).join(', ')

app/views/weekly_lists/show.html.slim
= content_for :sidebar, render('layouts/sidebar')
= cache @weekly_list, expires_in: 5.days
  section.content#weekday data-week=@weekly_list&.wednesday_date
    .box
      .box-header
        h3.box-title = "Browse releases for #{@weekly_list&.wednesday_date}"
      .box-body.table-responsive
        button.btn.btn-primary.toggle-filters#toggle-filters-button data-toggle="offcanvas" Show filters
        p style='margin-top: 2px;' Hint: you can click to on the logo on the header to toggle the filters sidebar
        table.table.table-bordered.dataTable#releases
          thead
            tr
              th Cover
              th Synopsis
              th Shipping date
              th Title
              th#editions Edition type
              th#publishers Publisher
              th.creators#writers Writers
              th.creators#artists Artists
              th.creators#cover_artists Cover artists
          tbody
            - @comics&.each do |comic|
              = cache comic, expires_in: 5.days
                tr data-preview= comic.preview
                  td
                    = link_to image_tag(comic.cover_thumbnail&.url, class: 'img-responsive', size: "215x330"), comic.cover_image, target: '_blank' if comic.cover_thumbnail
                  td
                    i.fa.fa-plus-circle.fa-2x#toggle_preview
                  td = comic.shipping_date
                  td
                    = link_to comic.humanized_title, comic_path(comic)
                  td = comic.humanized_item_type
                  td = comic.publisher&.name
                  td
                    - comic.writers&.each do |creator|
                      p
                        a href=creator_path(creator)
                          = creator.name
                  td
                    - comic.artists&.each do |creator|
                      p
                        a href=creator_path(creator)
                          = creator.name
                  td
                    - comic.cover_artists&.each do |creator|
                      p
                        a href=creator_path(creator)
                          = creator.name