config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#landing'
  get 'new_releases', to: 'weekly_lists#new_releases'
  get 'releases/:date', to: 'weekly_lists#show'
  resources :creators, only: [:index, :show]
  resources :comics, only: :show
  resources :publishers, only: :index

  get :api, to: 'static_pages#api_doc'
  get :about, to: 'static_pages#about'
  namespace :api do
    namespace :v1 do
      get :weekly_releases, to: "comics#weekly_releases"
      resources :comics, only: [:index]
      resources :publishers, only: [:index]
      resources :creators, only: [:index]
      get :creator, to: "creators#show"
    end
  end
end

app/views/layouts/_creators_filters.html.slim
li.treeview
  a 
    span Creators
    i.fa.fa-angle-left.pull-right
  ul.treeview-menu
    - creators_filters&.each do |creator|
      li
        a.filterable data-filter-type="creators"
          = creator.name

app/views/layouts/_editions_filters.html.slim
li.treeview
  a 
    span Edition types
    i.fa.fa-angle-left.pull-right
  ul.treeview-menu
    - Comic.item_types.each do |item_type|
      li
        a.filterable data-filter-type="editions"
          = item_type

app/views/layouts/_footer.html.slim
.main-footer.test-footer
  .pull-right.hidden-xs
    b
      = link_to '  About', about_path
    - if action_name == 'landing'
      span style="margin-left: 10px;"
        | background by
        = link_to ' Brandon Graham', 'https://twitter.com/royalboiler'
  strong
    = 'Copyright © 2016-2018'

app/views/layouts/_google_analytics.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', '#{Rails.application.secrets.google_analytics}', 'auto');
  ga('send', 'pageview');

app/views/layouts/_header.html.slim
header.main-header
  - if @creators_filters
    a.toggle-filters href='#' class="logo" data-toggle="offcanvas"
      span.logo-lg grepComics
  - else
    a href=new_releases_path class="logo"
      span.logo-lg grepComics
  nav.navbar.navbar-static-top role="navigation"
    a.calendar#wednesday-datepicker href="#"
      i.fa.fa-calendar
    .navbar-custom-menu
      ul.nav.navbar-nav
        li
          a href=creators_path Creators List
        li
          = link_to 'API', api_path

app/views/layouts/_publishers_filters.html.slim
li.treeview
  a 
    span Publishers
    i.fa.fa-angle-left.pull-right
  ul.treeview-menu
    - publishers_filters&.each do |publisher|
      li
        a.filterable data-filter-type="publishers"
          = publisher.name

app/views/layouts/_sidebar.html.slim
= cache @weekly_list, expires_in: 5.days
  aside.main-sidebar
    .sidebar
      ul.nav.sidebar-menu
        li.header Filters
        = render 'layouts/creators_filters', creators_filters: @creators_filters
        = render 'layouts/editions_filters'
        = render 'layouts/publishers_filters', publishers_filters: @publishers_filters
        li#applied_filters.header Applied filters

app/views/layouts/application.html.slim
doctype html
html
  head
    title grepComics
    = csrf_meta_tags
    = favicon_link_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = render 'layouts/google_analytics' if Rails.env.production?
    meta name='description' content="An easy way to browse weekly comics releases with the focus on the creators."
    meta name='keywords' content="comics, weekly releases, diamond comics, pull list, filters,
    search, graphic novels, trade paperbacks, wednesday comics, wednesday releases, api"

  body.fixed.skin-black.sidebar-collapse
    .wrapper
      = render 'layouts/header'
      = yield :sidebar
      .content-wrapper class="#{'landing-background' if action_name == 'landing'}"
        = yield
      = render 'layouts/footer'